### ISSUE TITLE
Cross Platform Compatibility?

### ISSUE THREAD

**Issue by gauravagarwalr** [poi-the-machine/the-machine#14]
Hi,

I was looking through the code and I felt that the cross platform aspects of the app weren't being addressed.
I was wondering why something like http://electron.atom.io/ wasn't considered. Especially when a lot of awesome apps are being built using it see Slack and Popcorn-Time.

**Comment by devloop0** [comment]
Javascript is a pretty terrible language to do advanced machine learning algorithms, but you are right in that we definitely need to make the app more portable. I'll leave this issue open, and if anyone wants to start developing for Linux, we can work on getting a unified code base.

**Comment by gauravagarwalr** [comment]
I am pretty sure it won't be as bad as C# or python! -> http://julialang.com/benchmarks.html

**Comment by gauravagarwalr** [comment]
> Javascript is a pretty terrible language to do advanced machine learning algorithms

Umm.. This says otherwise -> http://julialang.org/benchmarks/ . Also v8 tends to be upgraded in the performance factor! If you are concerned about the readability of the code I can try building a PoC on it.

**Comment by devloop0** [comment]
It's true that Javascript had relatively good performance, but it still doesn't beat native, and the Machine is pretty resource intensive, so it's going to require all the performance that it can get. In the fact, the reason we are using C# is because of the cool GUI effects and more importantly, if you look at our code, EmguCV is just a wrapper around native C++ calls to OpenCV, so the only overhead we are incurring is through the wrapped calls. What I meant by saying that Javascript is a terrible language to machine learning, is that, you can't get access to faster native speed, and the Machine learning libraries (in my opinion), are not as mature for Javascript as opposed to C++ or C#.
All that said, I recognize that it will be easier be easier to use cross platform frameworks with Javascript and I would love to be proven wrong with my assumptions, so if you do make a PoC and it's amazing, I would love to see it, but I would be hard-pressed to believe that it would the performance of Emgu CV's wrapped C++ calls. And as of now, we haven't done any optimizations, I think we may have turned off  optimizations in the default build, so if you got our code running, it is by no means at its maximal potential. 

Regarding atom/electron itself, correct me if I'm wrong, but it uses chromium to render everything so even if there was a one-to-one to translation, there would still be that overhead. Additionally, I would rather get a native feel for each app, so I would rather standardize the back end than the front end. And if we are standardizing the backend, C++ will probably be the language and directly calling the OpenCV api is what we would do.

However, if you are determined to make a web app, we would still accept it, I'm just addressing my concerns. If everyone else is okay with this, then I'll concede, I'd love to hear other perspectives on this.

**Comment by Xalaxis** [comment]
I think personally that due to the complex nature of this project, (lots of
different functions are planned to be implemented, some os specific) it
would be better to keep the clients development separate, and focus on
making them have a compatible back-end of some kind instead.

Hopefully I'll redo the old graphics we currently have on the project's
design to  illustrate this further.

**Comment by devloop0** [comment]
Hey Gaurav, if you want to talk about this more, let's discuss on Skype, we have a development chat there so everyone can communicate easily with everyone else.

**Comment by gauravagarwalr** [comment]
@devloop0 How do I get on the dev group on skype?

**Comment by Xalaxis** [comment]
@gauravagarwalr Development is recommencing and we're looking into cross-platform compatibility as a primary concern.  Just keeping you informed.

Joining the development chat won't be possible right now due to the nature of the project restarting - Hopefully this will be possible at some point in the future through.

**Comment by Xalaxis** [comment]
As I understand it, this issue has now been resolved through the move to Java.  Paging @devloop0 just in case.
